# Generated by Django 5.0.1 on 2026-02-02 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Роль пользователя', 'verbose_name_plural': 'Роли пользователей'},
        ),
        migrations.AddField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Администратор, который назначил роль', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Назначена пользователем'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание прав и назначения роли', null=True, verbose_name='Описание роли'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(db_index=True, help_text='Уникальное имя роли (например: admin, manager, user)', max_length=50, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Автоматически устанавливается при создании', verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Уникальный email для входа в систему', max_length=254, unique=True, verbose_name='Email адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Имя пользователя (до 50 символов)', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False для мягкого удаления аккаунта', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Разрешён ли доступ в Django Admin', verbose_name='Доступ в админку'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Полные права в системе', verbose_name='Суперпользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True, если пользователь подтвердил email через OTP код', verbose_name='Email подтверждён'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, help_text='Обновляется при каждом логине', null=True, verbose_name='Последний вход'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text='Фамилия пользователя (до 50 символов)', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, help_text='6-значный код для подтверждения email', max_length=6, null=True, verbose_name='OTP код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, help_text='После этого времени OTP код становится недействительным', null=True, verbose_name='Срок действия OTP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Хешированный пароль (bcrypt)', max_length=255, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Когда роль была назначена пользователю', verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(help_text='Роль, назначенная пользователю', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(help_text='Пользователь, которому назначена роль', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='idx_user_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_verified'], name='idx_user_status'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='idx_user_role'),
        ),
        migrations.AlterModelTable(
            name='role',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_roles',
        ),
    ]
