# Generated by Django 5.0.1 on 2025-11-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название элемента')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Бизнес-элемент',
                'verbose_name_plural': 'Бизнес-элементы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessRolesRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_permission', models.BooleanField(default=False, verbose_name='Чтение своих объектов')),
                ('read_all_permission', models.BooleanField(default=False, verbose_name='Чтение всех объектов')),
                ('create_permission', models.BooleanField(default=False, verbose_name='Создание')),
                ('update_permission', models.BooleanField(default=False, verbose_name='Обновление своих объектов')),
                ('update_all_permission', models.BooleanField(default=False, verbose_name='Обновление всех объектов')),
                ('delete_permission', models.BooleanField(default=False, verbose_name='Удаление своих объектов')),
                ('delete_all_permission', models.BooleanField(default=False, verbose_name='Удаление всех объектов')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='users.role', verbose_name='Роль')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access.businesselement', verbose_name='Бизнес-элемент')),
            ],
            options={
                'verbose_name': 'Правило доступа',
                'verbose_name_plural': 'Правила доступа',
                'ordering': ['role__name', 'element__name'],
                'unique_together': {('role', 'element')},
            },
        ),
    ]
