# Generated by Django 5.0.1 on 2026-02-02 13:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
        ('users', '0002_alter_role_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrolesrules',
            name='create_permission',
            field=models.BooleanField(default=False, help_text='Разрешено создавать новые объекты', verbose_name='Создание'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Когда правило было создано', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='delete_all_permission',
            field=models.BooleanField(default=False, help_text='Разрешено удалять любые объекты независимо от владельца', verbose_name='Удаление всех объектов'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='delete_permission',
            field=models.BooleanField(default=False, help_text='Разрешено удалять свои объекты (owner_id = user.id)', verbose_name='Удаление своих объектов'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='element',
            field=models.ForeignKey(help_text='Элемент, к которому применяются правила', on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access.businesselement', verbose_name='Бизнес-элемент'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='read_all_permission',
            field=models.BooleanField(default=False, help_text='Разрешено читать все объекты независимо от владельца', verbose_name='Чтение всех объектов'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='read_permission',
            field=models.BooleanField(default=False, help_text='Разрешено читать объекты, созданные пользователем (owner_id = user.id)', verbose_name='Чтение своих объектов'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='role',
            field=models.ForeignKey(help_text='Роль, для которой определяются права доступа', on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='users.role', verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='update_all_permission',
            field=models.BooleanField(default=False, help_text='Разрешено обновлять любые объекты независимо от владельца', verbose_name='Обновление всех объектов'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='update_permission',
            field=models.BooleanField(default=False, help_text='Разрешено обновлять свои объекты (owner_id = user.id)', verbose_name='Обновление своих объектов'),
        ),
        migrations.AlterField(
            model_name='accessrolesrules',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, help_text='Когда правило было последний раз изменено', verbose_name='Дата обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Автоматически устанавливается при создании', verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание назначения элемента', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='businesselement',
            name='name',
            field=models.CharField(db_index=True, help_text='Уникальное имя бизнес-элемента (например: products, orders)', max_length=100, unique=True, verbose_name='Название элемента'),
        ),
        migrations.AddIndex(
            model_name='accessrolesrules',
            index=models.Index(fields=['role', 'element'], name='idx_role_element'),
        ),
        migrations.AlterModelTable(
            name='accessrolesrules',
            table='access_roles_rules',
        ),
        migrations.AlterModelTable(
            name='businesselement',
            table='business_elements',
        ),
    ]
